name: ebtik_tok
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.1
  get_it: ^7.6.7
  http: ^1.2.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  svg_flutter: ^0.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icnos/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/Proxima Nova-Thin.otf
        - asset: assets/fonts/Proxima Nova-Semibold.otf
        - asset: assets/fonts/Proxima Nova-Extrabold.otf
        - asset: assets/fonts/Proxima Nova-Bold.otf
        - asset: assets/fonts/Proxima Nova-Black.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
